import type { Metadata } from "next";
import { Fira_Mono, Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import localFont from "next/font/local";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const firaMono = Fira_Mono({
  variable: "--font-fira-mono",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const zuume = localFont({
  variable: "--font-zuume",
  src: "../assets/zuume.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${firaMono.variable} ${outfit.variable} ${zuume.variable} antialiased dark selection:bg-primary`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
